# Node example configuration parameters
  /node_simulator/m: 0.1           # Node execution period
  /node_simulator/l: 0.3
  /node_simulator/d: 0.3
  /node_simulator/dt: 1.0
  /node_simulator/run_period: 0.1
  /node_simulator/initial_angle: 3.14
  /node_simulator/initial_angle: -0.1

  /node_controller/ts: 1.0 # controller T sampling = resolution of simulator
  /node_controller/Kc: 0.3
  /node_controller/Ti: 1.0
  # /node_controller/Ts: 0.3
  /node_controller/run_period: 0.1
  
  /subtick: 0.001 #in s
  /tick_multiplier: 10 #integeer
  /equilibrium_angle: 3.14