# SIMULATOR NODE
  /tb_simulator/Ta  : 0.150   # assigned
  /tb_simulator/Ts  : 0.010   # at least one decade more for now, tune later
  /tb_simulator/freq_multiplier  : 10  # for subtick: st = Ts/freq_multiplier
  /tb_simulator/endTime  : 100.0
  # Simlation State Initialization
  /tb_simulator/init_x  : 0.0 
  /tb_simulator/init_y  : 0.0 
  /tb_simulator/init_theta  : 0.00 
  /tb_simulator/init_v  : 0.0
  /tb_simulator/init_omega  : 0.0
  
# CONTROLLER NODE
  # TRAJECTORY
  # /tb_controller/R : 1.0
  /tb_controller/a : 5.0
  /tb_controller/T : 8.0
  /tb_controller/refreshperiod: 0.005

  # PID
  /tb_controller/pid_kc: 2.25945532459961
  /tb_controller/pid_ki: 0.0850437718651074

  # Feedback linearization parameters
  /tb_controller/xr: 0.3 #eta 
  /tb_controller/yr: 0.0  