# SIMULATOR NODE
  /tb_simulator/Ta  : 0.150   # assigned
  /tb_simulator/tick  : 0.0001   # at least one decade more for now, tune later
  # /tb_simulator/freq_multiplier  : 10  # for subtick: st = Ts/freq_multiplier
  /tb_simulator/endTime  : 250.0
  # Simlation State Initialization
  /tb_simulator/init_x  : 0.0 
  /tb_simulator/init_y  : 0.0 
  /tb_simulator/init_theta  : 0.00 
  /tb_simulator/init_v  : 0.0
  /tb_simulator/init_omega  : 0.0
  
# CONTROLLER NODE
  # TRAJECTORY
  # /tb_controller/R : 1.0
  /tb_controller/a : 5.0
  /tb_controller/T : 8.0
  /tb_controller/samplingperiod: 0.005
  # /tb_controller/wait: 5

  # PID
  /tb_controller/pid_kc: 2.1 #1 #1 #0.5
  /tb_controller/pid_ti: 28.6 #23.34 #0.1

  # Feedback linearization parameters
  /tb_controller/xr: 0.1 #eta 
  /tb_controller/yr: 0.0  

  # /tb_controller/shiftf: false