# Node example configuration parameters
  /tb_simulator/Ta  : 0.150   # assigned
  /tb_simulator/Ts  : 0.010   # at least one decade more for now, tune later
  /tb_simulator/freq_multiplier  : 10  # for subtick
  # Simlation State Initialization
  /tb_simulator/x0  : 0.0 
  /tb_simulator/y0  : 0.0 
  /tb_simulator/theta0  : 0.0 
  /tb_simulator/v0  : 0.0
  /tb_simulator/omega0  : 0.0

  /tb_test/v        : 0.5     # m/s
  /tb_test/omega    : 0.1     # rad/s
  /tb_test/period   : 1.1     # s
  # /traj_planner/a : 5.0
  # /traj_planner/T : 8.0